version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: spring-template-container
    restart: always
    environment:
      POSTGRES_USER: homedraw
      POSTGRES_PASSWORD: 1234homedraw
      POSTGRES_DB: homedrawdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: